name: Zuri chat testing pipeline

on:
  push:
    branches:
      - develop
      - main
      - master

env:
  NODE_VERSION: '12.x' # set this to the node version to use

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Send greeting
        run: echo ${{ github.head_ref }}
